server:
  port: 8080

spring:
  application:
    name: lifeos

  datasource:
    url: jdbc:h2:mem:lifeos
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
      

lifeos:
  jwt:
    secret: 58656c694f7346696e466c6f775365637265744b6579466f724a57545369676e696e675573696e674853323536
    expiration: 86400000

---
spring:
  config:
    activate:
      on-profile: mysql

  datasource:
    url: jdbc:mysql://localhost:3306/lifeos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  h2:
    console:
      enabled: false
